version: "3.9"

services:

  manager_redis:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    image: redis:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./docker/redis/data/:/data:rw

  ########  BEGIN  ########
  ######## PHP-CLI ########
  manager_php-cli:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    working_dir: /app
    image: ${DOCKER_REGISTRY_HOST}/cli:latest
    command: bash -c "sleep 10 && ssh-keyscan gitlab.alltel24.ru > ~/.ssh/known_hosts && composer install && php yii migrate --interactive=0"
    depends_on:
      manager_redis:
        condition: service_started
      manager_database:
        condition: service_healthy
    volumes:
      - ./src:/app:rw
      - /root/.ssh/bitbucket_key:/root/.ssh/bitbucket_key:ro
  ######## PHP-CLI ########
  ########   END   ########

  ########  BEGIN  ########
  ######## PHP-FPM ########
  manager_php-fpm:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    working_dir: /app
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    image: ${DOCKER_REGISTRY_HOST}/fpm:latest
    restart: always
    depends_on:
      manager_redis:
        condition: service_started
      manager_database:
        condition: service_healthy
    volumes:
      - ./src:/app:rw
      - ./docker/php:/usr/local/etc/php/custom.d
  ######## PHP-FPM ########
  ########   END   ########

  ########    BEGIN   ########
  ########     CRON   ########
  manager_cron:
    working_dir: /app
    image: ${DOCKER_REGISTRY_HOST}/cli:latest
    command: crond -f -d 7 -l 7 -L /var/log/cron.log
    restart: always
    depends_on:
      manager_redis:
        condition: service_started
    volumes:
      - ./src:/app:rw
      - ./docker/cron/start_up.sh:/etc/crontabs/www-data:rw
  ########    CRON    ########
  ########     END    ########

  manager_nginx:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    image: nginx:latest
    restart: always
    environment:
      EXTERNAL_DOMAIN: ${DOMAIN}
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    depends_on:
      - manager_php-fpm
    volumes:
      - ./src:/app:rw
      - ./docker/nginx/hosts:/etc/nginx/templates/
      - ./docker/nginx/logs:/var/log/nginx:rw
    networks:
      default:
        ipv4_address: ${HOST_NGINX}

  manager_database:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK}
          